### ISSUE TITLE
Is a complete offline installation considered? 

### ISSUE THREAD

**Issue by vocaloidat** [HandyOSS/HandyHost#50]
Is a complete offline installation considered? 
During the installation process, the Chinese government banned a large number of restrictions on external links needed for most of the installation process.

**Comment by alexsmith540** [comment]
Thats unfortunate. There are a lot of libraries/resources for the 3 projects that come from a variety of sources (go, kubernetes, nodejs, docker, sia, github, dvpn, akash and a slew of UI libraries). Sortof a large footprint when you add up 3 projects plus the UI. I'd guess some of these could be bundled and dumped somewhere accessible perhaps but its also not ideal. The main reason for not having an offline deploy is so that all the dependencies are downloaded/compiled from source on your machine with the latest versions. In addition, many of the major dependencies/blockchain projects are always kept up to date via the app with the latest major releases.
Thinking out loud here: Is it possible to use DVPN CLI on your computer while doing the install so you can download them all over vpn?

**Comment by vocaloidat** [comment]
Good idea. I will use the global vpn to install HandyHost
